"""
CEVA Animal Health - Data Assistant Streamlit App
Phase 2: Full integration with LangGraph agent
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import sys
from pathlib import Path

# Add agent directory to path
agent_path = Path(__file__).parent.parent / "agent"
sys.path.insert(0, str(agent_path))

from agent import build_agent, run_agent


# Cache the compiled agent (compile once, reuse)
@st.cache_resource
def get_agent():
    """Initialize and compile agent once"""
    return build_agent()


# START AGENT GENERATED CODE
def render_visualization(viz_type: str, columns: list, rows: list):
    """Render visualization based on type - GENERATED BY AGENT"""

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns=columns)

    # Pie chart
    fig = px.pie(
        df,
        names="bu_source",
        values="batch_count" if len(df.columns) > 1 else df.columns[0],
        title="Distribution"
    )
    st.plotly_chart(fig, use_container_width=True)
# END AGENT GENERATED CODE


def main():
    """Main Streamlit app"""

    # Page config
    st.set_page_config(
        page_title="CEVA Data Assistant",
        page_icon="🐾",
        layout="wide"
    )

    # Initialize session state
    if "last_result" not in st.session_state:
        st.session_state.last_result = None

    # Title
    st.title("🐾 CEVA Animal Health - Data Assistant")
    st.markdown("Ask questions about production data in natural language")

    st.markdown("---")

    # User input form
    with st.form("question_form"):
        question = st.text_input(
            "Ask a question:",
            placeholder="How many batches were produced by each business unit?",
            help="Enter your question in natural language"
        )
        submitted = st.form_submit_button("Analyze")

    # Process question
    if submitted and question:
        with st.spinner("🔄 Analyzing your question..."):
            try:
                # Get cached agent
                agent = get_agent()

                # Run agent
                result = run_agent(question, agent)

                # Store in session state
                st.session_state.last_result = result

                st.success("✅ Analysis complete!")

            except Exception as e:
                st.error(f"❌ Error: {e}")
                st.session_state.last_result = None

    # Display results
    if st.session_state.get("last_result"):
        result = st.session_state.last_result

        # Display SQL
        with st.expander("📝 Generated SQL Query", expanded=False):
            st.code(result.get("generated_sql", ""), language="sql")

        # Display visualization
        st.subheader("📊 Results")

        rows = result.get("query_results", [])
        columns = result.get("result_columns", [])
        viz_type = result.get("viz_type", "table")

        if rows and columns:
            try:
                # Call the agent-generated render_visualization function
                render_visualization(viz_type, columns, rows)
            except Exception as e:
                st.error(f"Chart rendering failed: {e}")
                st.warning("Showing table as fallback...")
                df = pd.DataFrame(rows, columns=columns)
                st.dataframe(df, use_container_width=True, hide_index=True)
        else:
            st.warning("No results returned from query")


if __name__ == "__main__":
    main()
