"""
CEVA Animal Health - Data Assistant Streamlit App
Phase 2: Full integration with LangGraph agent
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import sys
from pathlib import Path

# Add agent directory to path
agent_path = Path(__file__).parent.parent / "agent"
sys.path.insert(0, str(agent_path))

from agent import build_agent, run_agent


# Cache the compiled agent (compile once, reuse)
@st.cache_resource
def get_agent():
    """Initialize and compile agent once"""
    return build_agent()


# START AGENT GENERATED CODE
def render_visualization(viz_type: str, columns: list, rows: list):
    """Render visualization based on data - GENERATED BY AGENT"""
    import pandas as pd
    import streamlit as st
    import plotly.express as px

    df = pd.DataFrame(rows, columns=columns)

    # Bar chart for categorical comparison
    fig = px.bar(
        df,
        x="bu_source",
        y="batch_count",
        title="Batch Production by Business Unit",
        labels={
            "bu_source": "Business Unit",
            "batch_count": "Number of Batches"
        },
        color="bu_source",
        text="batch_count"
    )

    fig.update_traces(texttemplate='%{text}', textposition='outside')
    fig.update_layout(showlegend=False, xaxis_tickangle=0)

    st.plotly_chart(fig, use_container_width=True)
    st.caption(f"Total batches across {len(df)} business units: {df['batch_count'].sum():,}")# END AGENT GENERATED CODE


def main():
    """Main Streamlit app"""

    # Page config
    st.set_page_config(
        page_title="CEVA Data Assistant",
        page_icon="🐾",
        layout="wide"
    )

    # Initialize session state
    if "last_result" not in st.session_state:
        st.session_state.last_result = None

    # Title
    st.title("🐾 CEVA Animal Health - Data Assistant")
    st.markdown("Ask questions about production data in natural language")

    st.markdown("---")

    # User input form
    with st.form("question_form"):
        question = st.text_input(
            "Ask a question:",
            placeholder="How many batches were produced by each business unit?",
            help="Enter your question in natural language"
        )
        submitted = st.form_submit_button("Analyze")

    # Process question
    if submitted and question:
        with st.spinner("🔄 Analyzing your question..."):
            try:
                # Get cached agent
                agent = get_agent()

                # Run agent
                result = run_agent(question, agent)

                # Store in session state
                st.session_state.last_result = result

                st.success("✅ Analysis complete!")

            except Exception as e:
                st.error(f"❌ Error: {e}")
                st.session_state.last_result = None

    # Display results
    if st.session_state.get("last_result"):
        result = st.session_state.last_result

        # Display SQL
        with st.expander("📝 Generated SQL Query", expanded=False):
            st.code(result.get("generated_sql", ""), language="sql")

        # Display visualization
        st.subheader("📊 Results")

        rows = result.get("query_results", [])
        columns = result.get("result_columns", [])

        if rows and columns:
            try:
                # Call the agent-generated render_visualization function
                # Note: viz_type parameter is kept for signature compatibility but not used
                render_visualization("auto", columns, rows)
            except Exception as e:
                st.error(f"Chart rendering failed: {e}")
                st.warning("Showing table as fallback...")
                df = pd.DataFrame(rows, columns=columns)
                st.dataframe(df, use_container_width=True, hide_index=True)
        else:
            st.warning("No results returned from query")


if __name__ == "__main__":
    main()
