"""Generate Streamlit views - creates visualization code and updates streamlit_app.py"""

import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..agent import AgentState


# Path to streamlit app
STREAMLIT_APP_PATH = Path(__file__).parent.parent.parent / "streamlit-app" / "streamlit_app.py"
START_MARKER = "# START AGENT GENERATED CODE"
END_MARKER = "# END AGENT GENERATED CODE"


def has_time_column(columns: list) -> bool:
    """Check if any column appears to be time-related"""
    time_keywords = ["date", "time", "month", "year", "day", "week", "quarter", "period"]
    for col in columns:
        col_lower = str(col).lower()
        if any(keyword in col_lower for keyword in time_keywords):
            return True
    return False


def is_numeric_column(rows: list, col_index: int) -> bool:
    """Check if a column contains numeric values"""
    if not rows:
        return False
    for row in rows[:5]:
        if col_index < len(row):
            val = row[col_index]
            if val is not None and not isinstance(val, (int, float)):
                return False
    return True


def determine_viz_type(rows: list, columns: list) -> str:
    """Determine the best visualization type based on data characteristics"""

    if not rows or not columns:
        return "table"

    num_rows = len(rows)
    num_cols = len(columns)

    # Rule 1: Single row or many columns → table
    if num_rows == 1 or num_cols > 5:
        return "table"

    # Rule 2: Time column detected → line_chart
    if has_time_column(columns):
        return "line_chart"

    # Rule 3: 2 columns, ≤7 rows → pie_chart
    if num_cols == 2 and num_rows <= 7:
        return "pie_chart"

    # Rule 4: 2 columns, >7 rows → bar_chart
    if num_cols == 2 and num_rows > 7:
        return "bar_chart"

    # Rule 5: 2 numeric columns → scatter_plot
    if num_cols == 2 and is_numeric_column(rows, 0) and is_numeric_column(rows, 1):
        return "scatter_plot"

    # Default: bar_chart for multi-column comparisons
    if num_cols >= 2:
        return "bar_chart"

    return "table"


def generate_render_function_code(viz_type: str, columns: list) -> str:
    """Generate the Python code for render_visualization function"""

    code = '''def render_visualization(viz_type: str, columns: list, rows: list):
    """Render visualization based on type - GENERATED BY AGENT"""

    # Convert to DataFrame
    df = pd.DataFrame(rows, columns=columns)

'''

    if viz_type == "table":
        code += '''    # Table view
    st.dataframe(df, use_container_width=True, hide_index=True)
    st.caption(f"Showing {len(df)} rows")
'''

    elif viz_type == "bar_chart":
        code += f'''    # Bar chart
    fig = px.bar(
        df,
        x="{columns[0]}",
        y="{columns[1]}" if len(df.columns) > 1 else df.columns[0],
        title="Batches by Category"
    )
    st.plotly_chart(fig, use_container_width=True)
'''

    elif viz_type == "line_chart":
        code += f'''    # Line chart (time series)
    fig = px.line(
        df,
        x="{columns[0]}",
        y="{columns[1]}" if len(df.columns) > 1 else df.columns[0],
        markers=True,
        title="Trend over Time"
    )
    st.plotly_chart(fig, use_container_width=True)
'''

    elif viz_type == "pie_chart":
        code += f'''    # Pie chart
    fig = px.pie(
        df,
        names="{columns[0]}",
        values="{columns[1]}" if len(df.columns) > 1 else df.columns[0],
        title="Distribution"
    )
    st.plotly_chart(fig, use_container_width=True)
'''

    elif viz_type == "scatter_plot":
        code += f'''    # Scatter plot with trend line
    fig = px.scatter(
        df,
        x="{columns[0]}",
        y="{columns[1]}" if len(df.columns) > 1 else df.columns[0],
        trendline="ols",
        title="Correlation Analysis"
    )
    st.plotly_chart(fig, use_container_width=True)
'''

    else:
        code += '''    # Fallback to table
    st.warning(f"Unknown viz type: {viz_type}")
    st.dataframe(df, use_container_width=True)
'''

    return code


def update_streamlit_app(generated_code: str):
    """Update streamlit_app.py with generated visualization code"""

    # Read current file
    with open(STREAMLIT_APP_PATH, "r") as f:
        content = f.read()

    # Find markers
    pattern = re.compile(
        f"{re.escape(START_MARKER)}.*?{re.escape(END_MARKER)}",
        re.DOTALL
    )

    # Replace code between markers
    new_content = pattern.sub(
        f"{START_MARKER}\n{generated_code}{END_MARKER}",
        content
    )

    # Write back
    with open(STREAMLIT_APP_PATH, "w") as f:
        f.write(new_content)


def generate_streamlit_views(state: "AgentState") -> "AgentState":
    """Generate Streamlit visualization code and update the app file"""
    print("🎨 Generating Streamlit views...")

    rows = state.get("query_results", [])
    columns = state.get("result_columns", [])

    # Determine visualization type
    viz_type = determine_viz_type(rows, columns)
    print(f"→ Selected visualization: {viz_type}")

    # Generate code
    generated_code = generate_render_function_code(viz_type, columns)

    # Update streamlit app file
    try:
        update_streamlit_app(generated_code)
        print(f"✅ Updated {STREAMLIT_APP_PATH}")
    except Exception as e:
        print(f"❌ Failed to update streamlit app: {e}")

    # Store in state
    state["viz_type"] = viz_type
    state["streamlit_code"] = generated_code

    return state
